### ISSUE TITLE
[DevX bootstrap] Benchmark the speed download of the `devx` closure

### ISSUE THREAD

**Issue by yvan-sraka** [input-output-hk/devx#22]
When using GHA to turn `iohk/devx` into a shell to run, e.g. `cabal update, cabal build`, we take _a lot of time_ downloading stuff.

A lot of this time comes down to nix sequentially downloading a lot of data. We should build the store and export/import it instead to speed this up.

```
nix path-info --closure-size --human-readable $(nix print-dev-env --json .#ghc8107-static-minimal | jq -r .variables.out.value)
```
… will give us something like `2.5G`. That's a lot.

We can also enter the shell using
```
$ nix print-dev-env .#ghc8107-static-minimal > env.sh
$ bash --rcfile env.sh
```
(e.g. instead of `nix develop`).

We could pre-build the closure (e.g. from `result`), and store that as a `zstd` compressed archive:
```
nix-store --export $(nix-store -qR result) | zstd -z8T8 > out.zstd
```
And then re-import this as the first step in GHAs after setting up nix.

See for example this GHA: https://github.com/angerman/x/blob/c559ae0429bb69829a9c9cae8c21ab777461aaf2/.github/workflows/main.yml#L23-L66, which doesn't work properly yet (nix still ends up downloading stuff when trying to enter the shell; maybe this can be eliminated with the `env.sh` idea from above).

**Comment by yvan-sraka** [comment]
I wanted to measure the time latency improvement of such a hack, so I wrote a dumb python script:

```python
import os
import timeit

DEV_SHELLS = [
    "ghc8107",
    "ghc902",
    "ghc925",
    "ghc8107-minimal",
    "ghc902-minimal",
    "ghc925-minimal",
    "ghc8107-static-minimal",
    "ghc902-static-minimal",
    "ghc925-static-minimal",
]

T = {}
flake = "input-output-hk/devx" # vs. yvan-sraka/static-closure
for devShell in DEV_SHELLS:
    os.system(f"nix-collect-garbage -d")
    x = lambda number: round(timeit.timeit(lambda: os.system(
        f'nix develop "github:{flake}#{devShell}"\
        --no-write-lock-file --refresh --command true'
    ), number=number), 2)
    T[devShell] = {"bootstrap": x(1), "reload": x(10)}
print(T)

```

I currently exhaustively list working version of the `input-output-hk/devx` devShell, see issues #23 and #24. My machine (an iMac 24" M1) uses zw3rk.com cache (but I disable remote builder) as I wanted to match what I imagine the “defaults” user setting.

> n.b. I blindly choose Python because there is maybe a future where I want to possibly perform some basics statistics with `numpy` or display graphics with `matplotlib`!

The hack lives in this [`flake.nix`](https://github.com/yvan-sraka/speed-download-closure/blob/main/flake.nix) `shellHook`.

I'll post the benchmark result I got in this thread :)

**Comment by angerman** [comment]
This is good looking forward to the benchmarks!

**Comment by yvan-sraka** [comment]
The awaited benchmark that ran past night on my machine:

**Without** the _speed download hack_:
```yaml
ghc8107:
  bootstrap: 2155.54
  reload: 4.57
ghc902: broken
ghc925:
  bootstrap: 2005.21
  reload: 4.43
ghc8107-minimal:
  bootstrap: 1820.64
  reload: 3.59
ghc902-minimal:
  bootstrap: 1788.87
  reload: 3.33
ghc925-minimal:
  bootstrap: 1826.22
  reload: 3.76
ghc8107-static-minimal:
  bootstrap: 1774.84
  reload: 3.46
ghc902-static-minimal:
  bootstrap: 1780.89
  reload: 4.75
ghc925-static-minimal:
  bootstrap: 1871.04
  reload: 3.4
```

**With** the _speed download hack_:
```yaml
ghc8107: broken
ghc902: broken
ghc925: broken
ghc8107-minimal:
  bootstrap: 95.71
  reload: 37.74
ghc902-minimal:
  bootstrap: 100.58
  reload: 37.6
ghc925-minimal:
  bootstrap: 101.05
  reload: 33.25
ghc8107-static-minimal:
  bootstrap: 82.32
  reload: 30.61
ghc902-static-minimal:
  bootstrap: 91.1
  reload: 31.1
ghc925-static-minimal:
  bootstrap: 88.54
  reload: 27.21
```

First, there are few settings that are _“broken”_ and I should investigate why … Then, as you can see, it's a **big** improvement in bootstrap speed (I have a quite slow internet connection so that surely helps to increase the numbers) …

… but there is more work to do, as @angerman made me realize: wrapper derivation should not have to rely on `minio-client`! And reload time here is bad (the measure is 10x re-entering the shell): I should fix that, so it behaves at least like the **Without** the _speed download hack_ `nix develop` and even I believe I can potentially shave those numbers a bit. :)
